Assistant Archival Cleanup
dimagi/open-chat-studio pull request #1011
Opened 2024-12-19 16:12 UTC by stephherbers

## Description

[990](https://github.com/dimagi/open-chat-studio/issues/990)
Followup logic changes for assistant versioning archiving.

Now, when a assistant is archived that is a working version, all its versions is also archived and deleted from open AI.

Also from a UI standpoint. When it checks whether is can be archived, if its the working version it checks for all dependencies for all the versions not just the working version and displays everything that needs to be archived first. This way, the version won't be archived with the open AI deleted with something (exp or pipeline) still referencing it)

## User Impact

### Demo

### Docs

2025-01-06 07:43 UTC, SmittieC commented on apps/assistants/views.py
> +                    map(
I might be wrong, but I don't think we have to map the ids to strings?

2025-01-08 13:59 UTC, snopoke reviewed
After reviewing this and testing it locally I think we need to take a step back and look more holistically at how we trace references to objects and make that visible in the UI.

I've started a doc to make it easier to collaborate on the thoughts and ideas: https://docs.google.com/document/d/1Z09GNpO17izoVcRPGSmppNthFruyRJ0033T-RYvapoE/edit?tab=t.0

2025-01-09 20:09 UTC, stephherbers commented
noting that we are moving forward with changes from the doc so those commits will be coming in later and I will re-requests reviews

2025-01-16 07:26 UTC, SmittieC commented on apps/assistants/tests/test_delete.py
> +        experiment.is_default = True
Did you mean to make `exp_v2` the default here?

```python
exp_v2.is_default_version = True
```

2025-01-16 07:28 UTC, SmittieC commented on apps/assistants/tests/test_delete.py
> +        exp_v2 = experiment.create_new_version()
Nit: Since this will be version 2 (exp_v2), the previous `exp_v2` should be `exp_v1`

2025-01-16 07:45 UTC, SmittieC commented on apps/assistants/models.py
> +    def get_related_pipeline_node_queryset(self, assistant_ids: list = None):
These should check the experiments that the pipeline belongs to instead of the pipeline itself?

2025-01-16 07:48 UTC, SmittieC commented on apps/assistants/tests/test_delete.py
> +class TestAssistantArchival:
Nice tests. It would be great if we can add tests for pipelines using an assistant as well.

2025-01-20 20:39 UTC, stephherbers commented on apps/assistants/models.py
> +            nodes = Node.objects.filter(type="AssistantNode").filter(
@SmittieC since there is no "published" version of the pipeline-- is this the correct logic? For the demo you see that a pipeline with an experiment will only return the working experiment as the blocking issue for archiving the assistant and not the published experiment. 
Archiving the working experiment _will_ archive the published experiment, so this is really fine either way. But want to make sure we're on the same page

2025-01-21 11:18 UTC, SmittieC commented on apps/assistants/models.py
> +            nodes = Node.objects.filter(type="AssistantNode").filter(
We care about experiments being working or published in anycase, so I think it's fine. I do think that the nodes query should be 
```python
        nodes = Node.objects.filter(type="AssistantNode").filter(
            params__assistant_id=str(self.id),
            pipeline__is_archived=False,
        )
```
since if there's _any_ pipeline (version or not) that uses this assistant, we'd want to know the state of the experiment (if any) that is using that pipeline, if that makes sense? So we don't care about the pipeline version status, but we do care about the experiment's status _using_ that pipeline.

One other thing regarding the queries: We'd want to use the same filters in the experiments query on line 221 as we do in `get_related_experiments_queryset` to get experiments that are either the working or published versions.

Where do we archive the version of the experiment using the assistant or pipeline that uses the assistant in question? Is that part of this PR?

Two small nitty refactoring suggestions:
- Since this method is now returning an `Experiment` queryset, I'm wondering if the name can do with an update to make it clear that we're looking for pipeline type experiments that uses the assistant(s) in question?
- You can replace lines 207-218 with this
```python
        assistant_ids = assistant_ids if assistant_ids else [self.id]
        nodes = Node.objects.filter(type="AssistantNode").filter(
            Q(pipeline__working_version_id=None),
            params__assistant_id=str(self.id),
            pipeline__is_archived=False,
        )
```

2025-01-23 12:48 UTC, snopoke commented on apps/assistants/models.py
> +            nodes = Node.objects.filter(type="AssistantNode").filter(
I think that's mostly correct. But I would add that it's possible for a Pipeline to exist without being attached to an experiment (which would be the 'working version'). We would consider that blocking in terms of archiving the assistant.

In fact I think it's true that any 'working version' pipeline should block the archive (since we can assume that either it's not attached to an experiment or it's attached to the working version of the experiment).

That means that any pipeline working version should block archive OR any pipeline version that is attached to a 'published' experiment version.

2025-01-23 21:33 UTC, stephherbers commented on apps/assistants/models.py
> +            nodes = Node.objects.filter(type="AssistantNode").filter(
added https://github.com/dimagi/open-chat-studio/pull/1011#:~:text=%E2%80%A6-,a1e85df,-update%20views%20to

2025-01-24 12:21 UTC, SmittieC commented on apps/assistants/models.py
> +                is_default_version=True,
Do we care about working experiments as well?

2025-01-24 12:22 UTC, SmittieC commented on apps/assistants/views.py
> +            pipeline_nodes = assistant.get_related_pipeline_node_queryset()
Is this supposed to be here? It gets overwritten on line 231.

2025-01-24 18:48 UTC, snopoke reviewed
This is very close now. I'm going to check it out and test it locally.

2025-01-24 18:48 UTC, snopoke commented on apps/assistants/models.py
> +                    or self.get_related_experiments_with_pipeline_queryset().exists()
```suggestion
                    or version.get_related_experiments_with_pipeline_queryset().exists()
```

2025-01-24 18:48 UTC, snopoke commented on apps/assistants/models.py
> +        return self.experiment_set.filter(Q(working_version_id=None) | Q(is_default_version=True), is_archived=False)
nit: to avoid the repetition you could write this as:

```python
assistant_ids = assistant_ids or [self.id]
return Experiment.objects.filter(
    assistant_id__in=assistant_ids,
    Q(working_version_id=None) | Q(is_default_version=True),
    is_archived=False
)
```

2025-01-24 18:48 UTC, snopoke commented on apps/assistants/models.py
> +                is_default_version=True,
@stephherbers correct me if I'm wrong but I think we assume that a working version of an experiment must reference a working version of a pipeline which is covered in the query above.

Maybe a comment in code would help clarify the logic for posterity.

2025-01-24 18:48 UTC, snopoke commented on apps/assistants/models.py
> +            pipeline_ids = nodes.values_list("pipeline_id", flat=True)
Since we're going to execute the query anyway it doesn't make sense to do the exists check:
```suggestion
        if pipeline_ids := nodes.values_list("pipeline_id", flat=True):
```

2025-01-24 18:48 UTC, snopoke commented on apps/assistants/models.py
> +        return nodes
to avoid doing this query again and since we know this is an empty queryset by now, you can return `PipelineNode.objects.none()`.

Actually, to be consistent you should return `Experiment.objects.none()`

2025-01-24 18:48 UTC, snopoke commented on apps/assistants/tests/test_delete.py
> +    def test_archive_assistant_succeeds_with_released_related_experiment(self):
nit: maybe just me but I find this naming clearer
```suggestion
    def test_archive_assistant_succeeds_with_unpublished_related_experiment(self):
```

2025-01-24 18:48 UTC, snopoke commented on apps/assistants/tests/test_delete.py
> +        assistant.archive()
nit: you can also assert the return value:
```suggestion
        assert not assistant.archive()
```

2025-01-24 18:48 UTC, snopoke commented on apps/assistants/tests/test_delete.py
> +    def test_asistant_archive_blocked_by_published_related_experiment(self):
I don't thinks this test is testing what is says. There are no 'published' experiments in the test. It seems to be testing the same as `test_asistant_archive_blocked_by_working_related_experiment` except also testing that the assistant versions are archived.

2025-01-24 18:48 UTC, snopoke commented on apps/assistants/tests/test_delete.py
> +    def test_archive_assistant_succeeds_with_released_related_pipeline(self):
```suggestion
    def test_archive_assistant_succeeds_with_unpublished_related_pipeline(self):
```

2025-01-24 18:48 UTC, snopoke commented on apps/assistants/tests/test_delete.py
> +        exp_v2.save()
I don't think this is necessary since `create_new_version` won't make it the default version unless you pass `make_default=True`

2025-01-24 18:48 UTC, snopoke commented on apps/assistants/views.py
> +                    map(
we do because the pipeline params stores the values as strings

2025-01-27 15:12 UTC, snopoke commented on templates/assistants/partials/referenced_objects.html
> +  {% if pipeline_nodes %}
```suggestion
  {% if experiments_with_pipeline_nodes %}
```

2025-01-28 17:55 UTC, stephherbers commented on apps/assistants/tests/test_delete.py
> +        exp_v2.save()
here it is because it's the first version (other than the working), so it will make it the default version unless you set it to false

2025-01-28 19:16 UTC, stephherbers commented
@snopoke @SmittieC updated the screenshot in the description-- and I'll try for rearrqanging the confirmation modals a bit more before calling it quits. I believe this covers everything we discussed, plus updated tests

2025-01-29 10:50 UTC, snopoke requested changes
so close!

2025-01-30 08:42 UTC, snopoke approved these changes
Looks ready to merge once tests are passing:

```
=========================== short test summary info ============================
FAILED apps/assistants/tests/test_delete.py::TestAssistantArchival::test_archive_assistant_fails_with_working_related_versioned_pipeline_and_working_experiment - assert not True
 +  where True = <bound method OpenAiAssistant.archive of <OpenAiAssistant: >>()
 +    where <bound method OpenAiAssistant.archive of <OpenAiAssistant: >> = <OpenAiAssistant: >.archive
FAILED apps/assistants/tests/test_delete.py::TestAssistantArchival::test_archive_assistant_fails_with_working_related_pipeline - assert not True
 +  where True = <bound method OpenAiAssistant.archive of <OpenAiAssistant: >>()
 +    where <bound method OpenAiAssistant.archive of <OpenAiAssistant: >> = <OpenAiAssistant: >.archive
=========== 2 failed, 878 passed, 448 warnings in 323.87s (0:05:23) ============
```

2025-01-31 05:47 UTC, SmittieC approved these changes

2025-01-31 05:48 UTC, merged