Optional datetime injection
dimagi/open-chat-studio pull request #466
Opened 2024-06-19 08:57 UTC by SmittieC

Users now have to include the {current_datetime} somewhere in the prompt to inject it. 

Thoughts on this change?

![image](https://github.com/dimagi/open-chat-studio/assets/64970009/6d0a6355-6d00-48d0-a337-8bc4acdc2bc7)

TODO:
There's a pesky issue in one of the tests I still need to fix

2024-06-19 14:38 UTC, stephherbers requested changes

2024-06-20 10:42 UTC, SmittieC commented on apps/experiments/views/experiment.py
> +        required_variables.add("current_datetime")
How's this? https://github.com/dimagi/open-chat-studio/pull/466/commits/8e87a36c81e73b8224a0877c726418f0cfbdea3a

2024-06-25 12:52 UTC, stephherbers approved these changes

2024-06-25 12:52 UTC, stephherbers commented on apps/experiments/views/experiment.py
> +        required_variables.add("current_datetime")
🌟

2024-06-25 14:12 UTC, merged